transporting GithubBadge files to one top level
alisaitbilgi/Github-Badge pull request #1
Opened 2017-02-01 14:00 UTC by alisaitbilgi

2017-02-01 14:05 UTC, bulentzeki requested changes

2017-02-01 14:05 UTC, bulentzeki commented on imTest.js
> +// 1) SET USAGE:
No commented out code

2017-02-01 14:05 UTC, bulentzeki commented on package.json
> +    "react-scripts": "0.8.2",
what is react-scripts

2017-02-02 07:46 UTC, bulentzeki requested changes

2017-02-02 07:46 UTC, bulentzeki commented on src/App.js
> +const forkImage = require("/Users/alibilgi/Desktop/GithubBadge/public/styles/images/fork.png");
Use relative paths. 
For example:
`./projects/GithubBadge/public/styles/images/fork.png`

2017-02-02 07:46 UTC, bulentzeki commented on src/ContentContainer.js
> +const smallImage = require("/Users/alibilgi/Desktop/GithubBadge/public/styles/images/small.png");
Use relative paths.

2017-02-03 10:31 UTC, alisaitbilgi reviewed
Migration is almost completed

2017-02-03 10:52 UTC, bulentzeki requested changes

2017-02-03 10:52 UTC, bulentzeki commented on src/components/ContentPresenter.js
> +const smallImage = require("/Users/alibilgi/Desktop/GithubBadge/public/styles/images/small.png");
use relative path

2017-02-03 10:52 UTC, bulentzeki commented on src/components/ContentPresenter.js
> +let repos = [{}];
Do your really need these initializations?

2017-02-03 10:52 UTC, bulentzeki commented on src/components/ContentPresenter.js
> +                        <img src={users.avatar_url || "https://avatars2.githubusercontent.com/u/5779565?v=3&s=88"} alt="empty" />
You should read about what "alt" attribute is.

2017-02-03 10:52 UTC, bulentzeki commented on src/components/ContentPresenter.js
> +                        {repos[0] ? repos[0].name : "no recent repo activity"} {repos[0] ? "(" + repos[0].language + ")" : ""}
You always use` repos[0]`. Why is `repos` is an array?

2017-02-03 10:52 UTC, bulentzeki commented on src/containers/App.js
> +const forkImage = require("../../public/styles/images/fork.png");
why require? why not import?

2017-02-03 10:52 UTC, bulentzeki commented on src/containers/App.js
> +                    <img className="forkImage" src={forkImage} alt="empty"/>
alt attribute again

2017-02-03 10:52 UTC, bulentzeki commented on src/containers/FormContainer.js
> +// import {addUserName} from "../actions/addUsername";
No commented out code!

2017-02-03 10:52 UTC, bulentzeki commented on src/containers/FormContainer.js
> +  let url = [];
Why is this an array?

2017-02-03 10:59 UTC, alisaitbilgi commented on src/components/ContentPresenter.js
> +const smallImage = require("/Users/alibilgi/Desktop/GithubBadge/public/styles/images/small.png");
relative path's are used.

2017-02-03 11:00 UTC, alisaitbilgi commented on src/components/ContentPresenter.js
> +let repos = [{}];
i've changed them as:
let users;
let repos;

2017-02-03 11:00 UTC, alisaitbilgi commented on src/components/ContentPresenter.js
> +                        {repos[0] ? repos[0].name : "no recent repo activity"} {repos[0] ? "(" + repos[0].language + ")" : ""}
because I used promise.all() method while requesting to server, and as a result i'm getting an array with sized two.

2017-02-03 11:00 UTC, alisaitbilgi commented on src/containers/FormContainer.js
> +// import {addUserName} from "../actions/addUsername";
it's been altered

2017-02-03 11:02 UTC, alisaitbilgi commented on src/containers/FormContainer.js
> +  let url = [];
because the datas which i need are coming from different url's, i've requested to the server with an array of urls.

2017-02-03 11:03 UTC, bulentzeki commented on src/components/ContentPresenter.js
> +                        {repos[0] ? repos[0].name : "no recent repo activity"} {repos[0] ? "(" + repos[0].language + ")" : ""}
but you use repos[1] in nowhere?

2017-02-03 11:05 UTC, alisaitbilgi commented on src/components/ContentPresenter.js
> +                        <img src={users.avatar_url || "https://avatars2.githubusercontent.com/u/5779565?v=3&s=88"} alt="empty" />
"alt attribute" specifies an alternate text for an image, when the image cannot be displayed isn't it?

2017-02-03 12:00 UTC, bulentzeki approved these changes

2017-02-03 12:08 UTC, merged