sparkline is added, last version is ready
alisaitbilgi/Github-Badge pull request #5
Opened 2017-02-07 11:16 UTC by alisaitbilgi

In this update, sparkline is added and all requirements tried to be satisfied.

2017-02-07 12:07 UTC, alisaitbilgi reviewed
It's ready to be reviewed

2017-02-08 14:29 UTC, bulentzeki requested changes

2017-02-08 14:29 UTC, bulentzeki commented on public/styles/style.css
> +@media (max-width: 850px) {
why 850px? There are standards for media queries.

2017-02-08 14:29 UTC, bulentzeki commented on public/styles/style.css
> +    .main > nav {
Please learn what `>` does if you don't know.

2017-02-08 14:29 UTC, bulentzeki commented on src/components/HomePresenter.js
> +        <iframe src={path} className="content" scrolling="no" />
Just a suggestion
```
<iframe className="content" 
             src={this.props.takeUserName ? `/users/${this.props.takeUserName}` : "/users"} 
            scrolling="no" />
```

2017-02-08 14:29 UTC, bulentzeki commented on src/reducers/singleReducer.js
> +export default function singleReducer(state = I.fromJS({username: "", responseObject: I.List()}), action) {
Avoid initializations in reducer

2017-02-09 12:50 UTC, bulentzeki approved these changes

2017-02-09 13:11 UTC, merged